### ISSUE TITLE
Frequent login causing mailbox to be spammed

### ISSUE THREAD

**Issue by austinhuang0131** [akameco/PixivDeck#140]
[As Pixiv says,](https://www.pixiv.help/hc/articles/115000679588) users will receive an email whenever they log in, regardless of IP. However, PixivDeck logs my account in several times (eg. New search, view large picture, etc.), which means that I'll receive several emails, which means I get spammed by Pixiv. When checking Pixiv's account history, I see around 20 logins made by "smartphone app".

Could you just only log into the account once when I open the app, and just keep myself logged in during my use until quitting it, at least? (Or just keep the login status no matter quitting it or not, but that's a bit difficult.)

**Comment by austinhuang0131** [comment]
On a side note, the language selection box is mal-aligned.

![screen shot 2017-11-17 at 5 43 56 pm](https://user-images.githubusercontent.com/16656689/32972191-f5d9536e-cbbe-11e7-8a03-374a3e1bf29d.png)

**Comment by akameco** [comment]
Thank you for repoting @austinhuang0131 :)
I'm sorry. This is intentional.
This is because API's authentication is interrupted because pixiv's private API is used.
For this reason, I re-login for each request and get a token.
I'd like to fix this behavior, but there is no current solution.
Do you have any idea?

---

// I used the google translation. I am sorry if I made a mistake. The original is below.
ごめんなさい。これは意図的です。 なぜなら、pixivの非公開APIを使っているためAPIの認証が途切れてしまうからです。このため、リクエストごとに再ログインしてトークンを取得しています。この挙動を直したいですが、現状解決方法がありません。何か考えはりますか？

**Comment by akameco** [comment]
> On a side note, the language selection box is mal-aligned.

Thanks. I'll fix it soon.

**Comment by austinhuang0131** [comment]
It's fine to reply me in Japanese (Can read, can't write or speak).

I saw that you used the password to create a token. I think the token should have an expiry instead of being a one-time token (Aligning with most APIs), so is it possible to store this token?

**Comment by austinhuang0131** [comment]
[Here](https://github.com/alphasp/pixiv-api-client/blob/master/index.js#L90) is an example of using the refresh token. Using the refresh token to get a new access token doesn't send an email to my inbox.

**Comment by akameco** [comment]
Great!
I'll fix it to use refresh token :)
